# documentation: https://cal.com/docs
# slogan: Scheduling infrastructure for absolutely everyone.
# tags: cal.com, scheduling, database
# logo: svgs/calcom.svg
# port: 3000

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - calcom-postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - POSTGRES_DB=${POSTGRES_DATABASE:-calcom}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 20s
      retries: 10
  calcom:
    image: calcom/cal.com:latest
    depends_on:
      - postgres
    environment:
      - NEXTAUTH_SECRET=$SERVICE_BASE64_64_SECRET
      - CALENDSO_ENCRYPTION_KEY=$SERVICE_BASE64_64_SECRET
      - DATABASE_URL=postgres://$SERVICE_USER_POSTGRES:$SERVICE_PASSWORD_POSTGRES@postgres:5432/${POSTGRES_DATABASE:-calcom}
      - NEXT_PUBLIC_WEBAPP_URL=http://localhost:3000
      - NEXTAUTH_URL={NEXT_PUBLIC_WEBAPP_URL}/api/auth