# documentation: https://www.rabbitmq.com/documentation.html
# slogan: With tens of thousands of users, RabbitMQ is one of the most popular open source message brokers.
# tags: message broker, message queue, message-oriented middleware, MOM, AMQP, MQTT, STOMP, messaging
# logo: svgs/rabbitmq.svg
# port: 5672

services:
  rabbitmq:
    hostname: 'myrabbit'
    image: rabbitmq:3.12-management
    environment:
      - SERVICE_FQDN_RABBITMQ_5672
      - SERVICE_FQDN_RABBITMQMANAGEMENT_15672
      - RABBITMQ_DEFAULT_USER=$SERVICE_USER_RABBITMQ
      - RABBITMQ_DEFAULT_PASS=$SERVICE_PASSWORD_RABBITMQ
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
